from odoo import models, fields, api
from dateutil.relativedelta import relativedelta


class ContractManagement(models.Model):
    """
    This class is used to manage contracts between a buyer and a seller.
    A contract is generated by creating a new contract record.
    """
    _name = 'estate.contract.management'
    _description = 'Contract Management'

    name = fields.Char(
        string="Name", default=lambda self: self.env.context.get('name', ''),
        help="Name of the contract")
    duration = fields.Integer(string="Duration in Months", default=1,
                              help="Duration of the contract in months")
    start_date = fields.Date(string="Start Date", default=fields.Date.today(),
                             help="Start date of the contract")
    end_date = fields.Date(string="End Date", compute="_compute_end_date",
                           help="End date of the contract", store=True)

    # Start of relational fields
    ########################################################################

    clauses_ids = fields.One2many(
        'estate.contract.management.clause', 'contract_id', string="Clauses",
        help="List of clauses included in the contract")
    offer_id = fields.Many2one('property.offer', string="Offer",
                               default=lambda self: self.env.context.get(
                                   'offer_id', None),
                               help="Offer related to the contract")

    @api.depends('start_date', 'duration')
    def _compute_end_date(self):
        for rec in self:
            rec.end_date = rec.start_date + \
                relativedelta(months=rec.duration)


class Clause(models.Model):
    """
    This model is used to represent clauses included in a contract.
    """
    _name = 'estate.contract.management.clause'
    _description = 'Contract Clause'

    name = fields.Char(
        'Clause Name', required=True,  # Clause name, e.g. "Rent payment"
        help="Name of the clause included in the contract")
    description = fields.Text(
        'Description',  # Description of the clause
        help="Description of the clause, includes all the details needed")

    contract_id = fields.Many2one(
        'estate.contract.management', string="Contract",  # Contract the clause belongs to
        help="Contract the clause is included in")
